---
- name: Configure tomcat
  hosts: webserver
  tasks:
    - name: Call multiple child playbooks
      include: "{{item}}"
      with_items:
        - install_tomcat.yml
        - copy_tomcat_user.yml
        - change_port.yml 
        - restart_tomcat.yml
        - pause.yml 
        - check_tomcat_response.yml

