---
- name: Download docker images
  hosts: all
  tasks:
    - name: Download images
      docker_image:
        source: pull
        name: "{{item}}"
      with_items:
        - nginx
        - httpd
        - ghost
        - tomee



