---
- name: Configure apache2 on Ubuntu and httpd on Redhat
  hosts: all
  tasks:
    - name: Install apache2 on Ubuntu
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install httpd on Redhat
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
    - name: Edit the index.html file
      copy:
        content: "Welcome to IntelliQIT"
        dest: /var/www/html/index.html
    - name: Restart apache2 on Ubuntu
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"
    - name: Restart httpd on Redhat
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "RedHat"
    - name: Check apache2/httpd response on all managed nodes
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
       - http://172.31.10.57
       - http://172.31.18.218
       - http://172.31.16.244








